dataset:
    data_path: '/pfss/mlde/workspaces/mlde_wsp_PI_Mezini/jl17wali/HF_HOME/GQA'
    dataset_name: GQA
    split: testdev
    testing: False
    max_samples: 1000
    batch_size: 20
    start_sample: 0

codex:
    prompt : ./prompts/chatapi.prompt
results_dir : ./results/gqa/

load_models:
    maskrcnn: True
    clip: False
    glip: True
    owlvit: False
    tcl: False
    gpt3_list: False
    gpt3_qa: False
    gpt3_guess: False
    depth: True
    llama_list: True
    llama_qa: True
    llama_general: True
    blip: True
    saliency: False
    xvlm: True

fixed_code_file: ./prompts/fixed_code/blip2.prompt