dataset:
    data_path: '/pfss/mlde/workspaces/mlde_wsp_PI_Mezini/jl17wali/HF_HOME/OKVQA'
    dataset_name: OKVQA
    split: test
    testing: False
    max_samples: 1000
    batch_size: 20
    start_sample: 0

codex:
    prompt: ./prompts/benchmarks/okvqa.prompt
results_dir: ./results/okvqa/

load_models:
    maskrcnn: False
    clip: False
    glip: False
    owlvit: False
    tcl: False
    gpt3_list: False
    gpt3_qa: False
    gpt3_guess: False
    llama_list: True
    llama_qa: True
    llama_general: True
    llama_guess: True
    depth: False
    blip: True
    saliency: False
    xvlm: False

fixed_code_file: ./prompts/fixed_code/blip2.prompt