codex:
    model: codellama
    codellama_model_name: /pfss/mlde/workspaces/mlde_wsp_PI_Mezini/ya50pabo/models/manifests/registry.ollama.ai/library/codellama/latest
load_models:
    codex: False
    codellama: True